language: generic

sudo: false

addons:
  apt:
    packages:
      - cscope

install:
  - git clone --depth=1 https://github.com/thinca/vim-themis /tmp/themis
  - git clone https://github.com/vim/vim $HOME/vim
  - (if ! test -d $HOME/vim-7.4/bin; then cd $HOME/vim && git checkout . && git checkout v7.4 && ./configure --prefix=$HOME/vim-7.4 --enable-cscope && make && make install; fi)

cache:
  directories:
    - $HOME/vim-7.4

script:
  - (echo ':PlugInstall | :qa' | vim -u init.vim -e; errcode=$?; if [ $errcode = 1 ]; then echo "Returned 1, which is okay?"; else echo "Returned $errcode"; exit 255; fi)
  - THEMIS_ARGS='-u init.vim -e -s' /tmp/themis/bin/themis --reporter spec
  - PATH=$HOME/vim-7.4/bin/:$PATH THEMIS_ARGS='-u init.vim -e -s' /tmp/themis/bin/themis --reporter spec
