language: generic

sudo: false

addons:
  apt:
    packages:
      - cscope

install: ./travis_prep.sh

cache:
  directories:
    - $HOME/vim-7.4
    - $HOME/vim-8.0
    - $HOME/global

script:
  - (echo ':PlugInstall | :qa' | vim -u init.vim -e; errcode=$?; if [ $errcode = 1 ]; then echo "Returned 1, which is okay?"; else echo "Returned $errcode"; exit 255; fi)
  - vim --version
  - PATH=$HOME/global/bin/:$PATH /tmp/themis/bin/themis --reporter spec
  - $HOME/vim-7.4/bin/vim --version
  - PATH=$HOME/global/bin:$HOME/vim-7.4/bin/:$PATH /tmp/themis/bin/themis --reporter spec
  - $HOME/vim-8.0/bin/vim --version
  - PATH=$HOME/global/bin:$HOME/vim-8.0/bin/:$PATH /tmp/themis/bin/themis --reporter spec
