language: generic

sudo: false

addons:
  apt:
    packages:
      - cscope
      - global

install:
  - git clone --depth=1 https://github.com/thinca/vim-themis /tmp/themis
  - git clone https://github.com/vim/vim $HOME/vim
  - (if ! test -d $HOME/vim-7.4/bin; then cd $HOME/vim && git checkout . && git checkout v7.4 && ./configure --prefix=$HOME/vim-7.4 && make && make install; fi)

cache:
  directories:
    - $HOME/vim-7.4

script:
  - /tmp/themis/bin/themis --reporter spec
  - PATH=$HOME/vim-7.4/bin/:$PATH /tmp/themis/bin/themis --reporter spec
